### ISSUE TITLE
Rails 4.2 compatibilty

### ISSUE THREAD

**Issue by juggy** [rubysherpas/paranoia#155]
```
ArgumentError - wrong number of arguments (0 for 1):
   () Users/juggy/Documents/porkepic/vroom/core/app/models/core/base.rb:27:in `publish_after_destroy'
  activesupport (4.2.0.beta1) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.2.0.beta1) lib/active_support/callbacks.rb:222:in `call'
  activesupport (4.2.0.beta1) lib/active_support/callbacks.rb:222:in `block in halting_and_conditional'
  activesupport (4.2.0.beta1) lib/active_support/callbacks.rb:87:in `call'
  activesupport (4.2.0.beta1) lib/active_support/callbacks.rb:87:in `run_callbacks'
  paranoia (2.0.2) lib/paranoia.rb:51:in `destroy'
   () Users/juggy/Documents/porkepic/vroom/crm/app/controllers/crm/contact_data_controller.rb:34:in `destroy'
```

It seems that paranoia is incompatible with rails 4,2

**Comment by antonioparisi** [comment]
@juggy why this has been closed?
