### ISSUE TITLE
ArgumentError: wrong number of arguments (given 3, expected 4)

### ISSUE THREAD

**Issue by FlowerWrong** [rubysherpas/paranoia#370]
When I create a record, it will raise `ArgumentError: wrong number of arguments (given 3, expected 4)`.

eg: `User.create(name:'haha')`

ruby: 2.3.3
rails: 5.1.0.alpha

**Comment by BenMorganIO** [comment]
Thanks for posting this! :+1:

Do you have a backtrace I could use (big wall of text)? Also, which version of paranoia are you using? C&P from Gemfile.lock will be helpful.

**Comment by BenMorganIO** [comment]
This may be related to: https://github.com/rubysherpas/paranoia/pull/365

**Comment by FlowerWrong** [comment]
Hi, @BenMorganIO , no more backtrace, I am using the the `gem "paranoia", "~> 2.2"` version.

**Comment by FlowerWrong** [comment]
```ruby
GIT
  remote: git://github.com/FlowerWrong/impressionist.git
  revision: b128685a20e339e80fce1da662f3308ee303338c
  specs:
    impressionist (1.5.2)
      nokogiri (~> 1.6)

GIT
  remote: git://github.com/github/gemoji.git
  revision: f394c85d80b3ed7a1146683a72c13e4e8985f6ce
  specs:
    gemoji (3.0.0.rc1)

GIT
  remote: git://github.com/mbleigh/acts-as-taggable-on.git
  revision: 8e64c3d4a81cfbb8af621228eae36a65c1f94501
  specs:
    acts-as-taggable-on (4.0.0)
      activerecord (>= 4.0)

GIT
  remote: git://github.com/rails/rails.git
  revision: c873746c506e193cf6294d8919d464997d54eadb
  specs:
    actioncable (5.1.0.alpha)
      actionpack (= 5.1.0.alpha)
      nio4r (~> 1.2)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.0.alpha)
      actionpack (= 5.1.0.alpha)
      actionview (= 5.1.0.alpha)
      activejob (= 5.1.0.alpha)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.0.alpha)
      actionview (= 5.1.0.alpha)
      activesupport (= 5.1.0.alpha)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.0.alpha)
      activesupport (= 5.1.0.alpha)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (5.1.0.alpha)
      activesupport (= 5.1.0.alpha)
      globalid (>= 0.3.6)
    activemodel (5.1.0.alpha)
      activesupport (= 5.1.0.alpha)
    activerecord (5.1.0.alpha)
      activemodel (= 5.1.0.alpha)
      activesupport (= 5.1.0.alpha)
      arel (~> 7.0)
    activesupport (5.1.0.alpha)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    rails (5.1.0.alpha)
      actioncable (= 5.1.0.alpha)
      actionmailer (= 5.1.0.alpha)
      actionpack (= 5.1.0.alpha)
      actionview (= 5.1.0.alpha)
      activejob (= 5.1.0.alpha)
      activemodel (= 5.1.0.alpha)
      activerecord (= 5.1.0.alpha)
      activesupport (= 5.1.0.alpha)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.1.0.alpha)
      sprockets-rails (>= 2.0.0)
    railties (5.1.0.alpha)
      actionpack (= 5.1.0.alpha)
      activesupport (= 5.1.0.alpha)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)

GIT
  remote: git://github.com/redis-store/redis-rails.git
  revision: 26cb7b5f782c69d1b76b78ce10bd3b7d68df20ab
  specs:
    redis-rails (5.0.1)
      redis-actionpack (~> 5.0.0)
      redis-activesupport (~> 5.0.0)
      redis-store (~> 1.2.0)

GEM
  remote: https://rubygems.org/
  specs:
    arel (7.1.4)
    ast (2.3.0)
    autoprefixer-rails (6.5.3.1)
      execjs
    awesome_nested_set (3.1.1)
      activerecord (>= 4.0.0, < 5.1)
    awesome_print (1.7.0)
    bcrypt (3.1.11)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    brakeman (3.4.1)
    builder (3.2.2)
    bullet (5.4.2)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.10.0)
    byebug (9.0.6)
    carrierwave (1.0.0.rc)
      activemodel (>= 4.0.0)
      activesupport (>= 4.0.0)
      mime-types (>= 1.16)
    code_analyzer (0.4.7)
      sexp_processor
    coderay (1.1.1)
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.11.1)
    concurrent-ruby (1.0.2)
    connection_pool (2.2.1)
    debug_inspector (0.0.2)
    devise (4.2.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.1)
      responders
      warden (~> 1.2.3)
    devise-i18n (1.1.1)
    domain_name (0.5.20161129)
      unf (>= 0.0.5, < 1.0.0)
    easy_translate (0.5.0)
      json
      thread
      thread_safe
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.1)
    execjs (2.7.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    ffaker (2.3.0)
    ffi (1.9.14)
    font-awesome-rails (4.7.0.0)
      railties (>= 3.2, < 5.1)
    foreman (0.82.0)
      thor (~> 0.19.1)
    formatador (0.2.5)
    github-markup (1.4.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    guard (2.14.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    hashie (3.4.6)
    highline (1.7.8)
    hiredis (0.6.1)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    i18n-tasks (0.9.6)
      activesupport (>= 4.0.2)
      ast (>= 2.1.0)
      easy_translate (>= 0.5.0)
      erubis
      highline (>= 1.7.3)
      i18n
      parser (>= 2.2.3.0)
      term-ansicolor (>= 1.3.2)
      terminal-table (>= 1.5.1)
    jbuilder (2.6.1)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    jquery-rails (4.2.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (2.0.2)
    jwt (1.5.6)
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kaminari-i18n (0.4.0)
      kaminari
      rails
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.10)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    metaclass (0.0.4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_magick (4.6.0)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    mocha (1.2.1)
      metaclass (~> 0.0.1)
    multi_json (1.12.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    mysql2 (0.4.5)
    nenv (0.3.0)
    netrc (0.11.0)
    nio4r (1.2.1)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oauth2 (1.2.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.3.1)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-github (1.1.2)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.1)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    paranoia (2.2.0)
      activerecord (>= 4.0, < 5.1)
    parser (2.3.3.1)
      ast (~> 2.2)
    powerpack (0.1.1)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pundit (1.1.0)
      activesupport (>= 3.0.0)
    rack (2.0.1)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails-dom-testing (2.0.1)
      activesupport (>= 4.2.0, < 6.0)
      nokogiri (~> 1.6.0)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-i18n (5.0.1)
      i18n (~> 0.7)
      railties (~> 5.0)
    rails-timeago (2.15.0)
      actionpack (>= 3.1)
      activesupport (>= 3.1)
    rails_best_practices (1.17.0)
      activesupport
      code_analyzer (>= 0.4.3)
      erubis
      i18n
      json
      require_all
      ruby-progressbar
    rails_real_favicon (0.0.6)
      json (>= 1.7, < 3)
      rails (>= 3.1)
      rest-client (~> 2.0)
      rubyzip (~> 1)
    rainbow (2.1.0)
    rake (12.0.0)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    redis (3.3.2)
    redis-actionpack (5.0.1)
      actionpack (>= 4.0, < 6)
      redis-rack (>= 1, < 3)
      redis-store (>= 1.1.0, < 1.4.0)
    redis-activesupport (5.0.1)
      activesupport (>= 3, < 6)
      redis-store (~> 1.2.0)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (2.0.0)
      rack (~> 2.0)
      redis-store (~> 1.2.0)
    redis-store (1.2.0)
      redis (>= 2.2)
    require_all (1.3.3)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    rest-client (2.0.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rolify (5.1.0)
    rubocop (0.46.0)
      parser (>= 2.3.1.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.8.1)
    rubyzip (1.2.0)
    rucaptcha (1.2.0)
      railties (>= 3.2)
    sass (3.4.22)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sexp_processor (4.7.0)
    shellany (0.0.1)
    sidekiq (4.2.7)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (~> 3.2, >= 3.2.1)
    slop (3.6.0)
    spring (2.0.0)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    term-ansicolor (1.4.0)
      tins (~> 1.0)
    terminal-table (1.7.3)
      unicode-display_width (~> 1.1.1)
    thor (0.19.4)
    thread (0.2.2)
    thread_safe (0.3.5)
    tilt (2.0.5)
    tins (1.13.0)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.4)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)
    unicode-display_width (1.1.1)
    uniform_notifier (1.10.0)
    warden (1.2.6)
      rack (>= 1.0)
    web-console (3.4.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      debug_inspector
      railties (>= 5.0)
    websocket-driver (0.6.4)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)

PLATFORMS
  ruby

DEPENDENCIES
  acts-as-taggable-on!
  awesome_nested_set
  awesome_print
  bootstrap-sass
  brakeman
  bullet
  byebug
  carrierwave (>= 1.0.0.rc, < 2.0)
  coffee-rails (~> 4.2)
  devise
  devise-i18n
  ffaker
  font-awesome-rails
  foreman
  gemoji!
  github-markup
  guard-livereload
  hiredis
  i18n-tasks
  impressionist!
  jbuilder (~> 2.5)
  jquery-rails
  kaminari
  kaminari-i18n
  listen (~> 3.0.5)
  method_source
  mini_magick
  mocha
  mysql2 (>= 0.3.18, < 0.5)
  omniauth
  omniauth-github
  paranoia (~> 2.2)
  pundit
  rails!
  rails-i18n
  rails-timeago
  rails_best_practices
  rails_real_favicon
  redis
  redis-namespace
  redis-rails!
  rolify
  rubocop
  rucaptcha
  sass-rails (~> 5.0)
  sidekiq
  spring
  spring-watcher-listen (~> 2.0.0)
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console

RUBY VERSION
   ruby 2.3.3p222

BUNDLED WITH
   1.13.6
```

**Comment by deepj** [comment]
@BenMorganIO Here is my backtrack (the latest paranoia master -- core and Rails 5.1 master)

```
ArgumentError:
            wrong number of arguments (given 3, expected 4)
          # ~/.gem/ruby/2.4.0/bundler/gems/paranoia-6972b229e298/lib/paranoia.rb:268:in `build_relation'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/validations/uniqueness.rb:17:in `validate_each'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activemodel/lib/active_model/validator.rb:150:in `block in validate'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activemodel/lib/active_model/validator.rb:147:in `each'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activemodel/lib/active_model/validator.rb:147:in `validate'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:420:in `block in make_lambda'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:204:in `block (2 levels) in halting'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:608:in `block (2 levels) in default_terminator'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:607:in `catch'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:607:in `block in default_terminator'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:205:in `block in halting'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:514:in `block in invoke_before'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:514:in `each'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:514:in `invoke_before'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:137:in `run_callbacks'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:817:in `_run_validate_callbacks'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activemodel/lib/active_model/validations.rb:405:in `run_validations!'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activemodel/lib/active_model/validations/callbacks.rb:111:in `block in run_validations!'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:138:in `run_callbacks'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/callbacks.rb:817:in `_run_validation_callbacks'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activemodel/lib/active_model/validations/callbacks.rb:111:in `run_validations!'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activemodel/lib/active_model/validations.rb:335:in `valid?'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/validations.rb:65:in `valid?'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/validations.rb:82:in `perform_validations'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/validations.rb:50:in `save!'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/transactions.rb:324:in `block in save!'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `block in transaction'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:186:in `within_new_transaction'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/transactions.rb:211:in `transaction'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/transactions.rb:324:in `save!'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activerecord/lib/active_record/suppressor.rb:46:in `save!'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/configuration.rb:18:in `block in initialize'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/evaluation.rb:15:in `create'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:9:in `tap'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:9:in `result'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/factory.rb:42:in `run'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
          # ~/.gem/ruby/2.4.0/bundler/gems/rails-e55fac51d93f/activesupport/lib/active_support/notifications.rb:166:in `instrument'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:28:in `run'
          # ~/.gem/ruby/2.4.0/gems/factory_girl-4.7.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
```

**Comment by BenMorganIO** [comment]
Cool! I had a feeling this was fixed, but now that I have the backtrace I can confirm that it's fixed in master. :tada:

See: https://github.com/rubysherpas/paranoia/pull/366

**Comment by deepj** [comment]
Thanks!

**Comment by BenMorganIO** [comment]
@FlowerWrong does this help you?

**Comment by deepj** [comment]
@BenMorganIO In our case it's fixed by #366. Thanks!

**Comment by rmachielse** [comment]
@BenMorganIO rails 5.1.0.beta1 is out now. We are now using the 2-2-stable branch to try the new rails beta, but that branch seems outdated with the core branch. We need both #366 and #377 to get our tests to pass. Can you update 2-2-stable with core or the other way around or something? That or another solution would be greatly appreciated

**Comment by BenMorganIO** [comment]
@rmachielse I think #366 was merged into 2-2-stable and @jhawthorn just got #384 into `master` which appears to be the same as #366.

As for #377, maybe use master, as we're not planning a 2.3 anytime soon. Or I could backport this to 2-2-stable.

**Comment by rmachielse** [comment]
@BenMorganIO thanks, the core branch is now indeed up to date. Unfortunately we are still having failing tests. The `after_update_commit` hook is not being called when destroying a record through paranoia, while that used to be the case before. I wonder if that's a bug in rails 5.1
