### ISSUE TITLE
the files list includes entire gem as a dependency 

### ISSUE THREAD

**Issue by jasonfb** [rubysherpas/paranoia#525]
all gemfiles are included by default....

these should not include testing files and only include the core library files..

https://github.com/rubysherpas/paranoia/blob/b6b51672fff64172c47fe5669efb773910a41bc4/paranoia.gemspec#L32

as a result, when you try to deploy it to Heroku,  you get:

```

remote:  !     LoadError: cannot load such file -- rspec/expectations
remote:  !     /tmp/build_3385c548/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
remote:  !     /tmp/build_3385c548/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
remote:  !     /tmp/build_3385c548/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
remote:  !     /tmp/build_3385c548/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
remote:  !     /tmp/build_3385c548/vendor/bundle/ruby/2.7.0/gems/paranoia-2.4.3/lib/paranoia/rspec.rb:1:in `<main>'

```

https://gist.github.com/jasonfb/20c3b0a85baf59824fddcdfbc5a7b5f4

**Comment by mathieujobin** [comment]
will be released as v2.5.2
